### ISSUE TITLE
Object diffing broken

### ISSUE THREAD

**Issue by emichael** [uwplse/dviz#23]
Might relate to #10.

When you have an object `foo` with some fields and it is cleared or set to `null`, what gets rendered is a version of the previous `foo` with all of the fields set to `null`. This happens recursively as well, so if the field in `foo` was itself a complex object, you see the entire structure remains, just with all of the values set to `null`.

Here's a version of `PingServer` that should illustrate this well.

```java
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = true)
public class PingServer extends Node {
    private final PingApplication app = new PingApplication();

    private Map<String, String> foo = new HashMap<>();

    {
        foo.put("bar", "baz");
    }

    /* -------------------------------------------------------------------------
        Construction and Initialization
       -----------------------------------------------------------------------*/
    public PingServer(Address address) {
        super(address);
    }

    @Override
    public void init() {
        // No initialization necessary
    }

    /* -------------------------------------------------------------------------
        Message Handlers
       -----------------------------------------------------------------------*/
    private void handlePingRequest(PingRequest m, Address sender) {
        foo.clear();

        Pong p = app.execute(m.ping());
        send(new PongReply(p), sender);
    }
}
```

Run `./run-tests.py -l0 -d 1 1 GET:foo` and deliver the `Ping` to the server. You can also try replacing `foo.clear()` with `foo = null`, same behavior.

**Comment by dwoos** [comment]
Now that we're not displaying updates, it makes more sense to just replace a node's state with the state from the message and just use the computed diffs for underlines in the state display. We're doing that now, so this (and any similar issues) should be fixed.
